### ISSUE TITLE
Deepin v20 / Debian 10 - nvidia driver not recognized

### ISSUE THREAD

**Issue by cirospaciari** [Nightmayr-snaps/yuzu-snap#12]
I tried to install the snap in Deepin v20 (Debian 10) Kernel 5.3 but i get this error:

![image](https://user-images.githubusercontent.com/6379399/89845094-ec36bc00-db53-11ea-8012-797de27ff177.png)
![image](https://user-images.githubusercontent.com/6379399/89845130-007ab900-db54-11ea-856f-7c551a377277.png)
![image](https://user-images.githubusercontent.com/6379399/89845186-2a33e000-db54-11ea-95f0-9c6aee156334.png)

**Comment by Nightmayr** [comment]
Hi @cirospaciari, I'm not too sure what's causing that problem for you. Your hardware looks good to me. I'm also using an Nvidia GPU and the main difference between my setup and yours is the driver version. I'm using nvidia driver 440.100, could you try updating your driver to this version? (I think that may be the reason behind the "or you do not have the latest graphics driver" message). 

I think these instructions should apply to you being on a Debian 10 Buster based distro: https://wiki.debian.org/NvidiaGraphicsDrivers#Version_440.100_.28via_buster-backports.29

**Comment by cirospaciari** [comment]
I use Deepin 20 (1000) last version, all drivers updated, (based in Debian 10.4). I will try add buster-backports as source list and install the latest driver.

**Comment by Nightmayr** [comment]
Strange, I'm able to see my GPU under Vulkan backend, can't see anything thats different aside from your GPU being a 1070 and mine being a 2080ti (I wouldn't expect this to make a difference) as well as the operating system. I'll try to see if I can get some time to set the snap up on Deepin 20 but I would expect it to function the same as Ubuntu 20.04 (distro I'm using).

Just to figure out if this problem is also affecting other snaps for you or is just a problem with yuzu, would you be able to download the `dolphin-emulator` (either beta or edge channels, as stable doesn't have a vulkan backend), and check whether your GPU is recognised when selecting the Vulkan backend from the graphics options. 

Sorry that I'm unable to identify the problem immediately, snap with nvidia vulkan isn't as straightforward as Intel/AMD due to the proprietary driver. Hopefully we can figure this out, as I agree with your comment about the snap being a painless method to install yuzu compared to building from source for end users.

**Comment by cirospaciari** [comment]
Hi, i get one update to kernel 5.4 and new drivers. All working now!
![image](https://user-images.githubusercontent.com/6379399/91368635-02917880-e7e0-11ea-9760-feeb5ed8b9f6.png)
![image](https://user-images.githubusercontent.com/6379399/91368654-0fae6780-e7e0-11ea-9e8f-ce4385219896.png)

**Comment by Nightmayr** [comment]
Thanks for the update, I'm wondering why updating the kernel would have fixed the problem 🤔. Glad it's working for you though
