### ISSUE TITLE
Controller - Unable to create Profiles

### ISSUE THREAD

**Issue by RickAndTired** [Nightmayr-snaps/yuzu-snap#14]
Version 0-376
Ubuntu 20.04.1
Ryzen 5 2600
AMD RX 570

In the Controls configuration

I am unable to type anything inside of the Profile drop down
Clicking the Profile drop down does nothing
Clicking Save does nothing
Clicking New does nothing
Clicking Delete does nothing

I get these messages when running the yuzu-snap from the terminal
```
(yuzu:11948): Gtk-WARNING **: 11:21:48.753: GTK+ module /snap/yuzu/79/usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 11:21:48.753: Failed to load module "canberra-gtk-module"

(yuzu:11948): Gtk-WARNING **: 11:21:48.754: GTK+ module /snap/yuzu/79/usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 11:21:48.754: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
```

**Comment by Nightmayr** [comment]
I can replicate this behaviour on my end as well. I think this is most likely a bug with the application code (upstream) rather than the snap packaging, as I tested the pre-built binary and saw the same behaviour (https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-376).

The warnings you see in the terminal are unrelated to this problem and should be harmless

**Comment by RickAndTired** [comment]
After checking Yuzu's Discord it looks like it's just not a bug, just not finished yet
