### ISSUE TITLE
Latest yuzu from snap fails to start

### ISSUE THREAD

**Issue by boriseto** [Nightmayr-snaps/yuzu-snap#41]
Trying to run it from terminal I get the following:
```
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
Cannot mix incompatible Qt library (5.12.8) with this library (5.15.2)
Aborted
```
Trying it with latest app image works

**Comment by Nightmayr** [comment]
I've published a snap to the candidate channel that you might be interested in taking a look at. It's essentially the new approach I intend to use for yuzu and many of my other Qt snaps like Citra, RPCS3, melonds (and probably more in the future) where it uses a content snap to get the Qt dependencies. Because the Qt is built and patched by me, in my testing it does allow for previous broken functionality to work and improvements in other areas:

- The "Open Yuzu folder" option and other similar buttons should now open a file manager window at the yuzu folder.
- Both yuzu and the content snap use lzo compression so should result in quicker startup times
- Theming should be fixed on KDE, with file chooser windows working properly. (xdg-portal-kde file choosers arent being used hopefully can transition to these when they are less buggy)
- Portal file choosers are used on GTK desktops like GNOME, meaning `removable-media` interface doesn't need to be connected to access external devices
- Because the content snap contains the Qt dependencies, the yuzu snap is able to shrink to 29MB (with lzo compression) compared to the current stable channel release of 306MB (without lzo compression), this makes a difference if using any of my other snaps that use Qt as they should also shrink similar to yuzu once the changes have been made.
- Not currently in the content snap but hopefully soon is the addition of QGnomePlatform and adwaita-qt for better GNOME integration

Some of these may not be to interesting to you but just informing you about these changes as I did allude to them in the previous comment.

**Comment by boriseto** [comment]
- the file manager is indeed from the kde de
- it more than halved startup times for me
- dark theme present now on kde
- that one I can't test it cause I don't use it
- definitely an improvement
- and that I can't test
I guess you can fully close the issue and if you want we can create separate issues for better organization (for you that is :) )

**Comment by Nightmayr** [comment]
Awesome, thanks for testing and providing feedback. I'll be merging this into the master branch soon. Agreed I'll close this issue and if any other issues arise from this change they can be tracked in a separated issue.
